export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  DB_ADMIN: "DB_ADMIN",
  ALL_LOC_ADMIN: "ALL_LOC_ADMIN",
  LOC_ADMIN: "LOC_ADMIN",
  OPERATOR: "OPERATOR",
};


// src/constants/abac.js

// Resources
export const RESOURCE_TYPE = {
  MANAGE_DASHBOARD: "MANAGE_DASHBOARD",
  MANAGE_ROLE: "MANAGE_ROLE",
  MANAGE_LOCATION: "MANAGE_LOCATION",
  MANAGE_OPERATOR: "MANAGE_OPERATOR",
  MANAGE_POLICY: "MANAGE_POLICY",
};

// Actions
export const ACTION = {
  VIEW: "VIEW",
  GET: "GET",
  GET_ALL: "GET_ALL",
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  DELETE_ALL: "DELETE_ALL",
  DISABLE: "DISABLE",
  ENABLE: "ENABLE",
};


