export const ROLES = {
    ADMIN: 'ROLE_ADMIN',
    USER: 'ROLE_USER',
    LIBRARIAN: 'ROLE_LIBRARIAN',
    MEMBER: 'ROLE_MEMBER',
    ACCOUNTANT: 'ROLE_ACCOUNTANT',
}

export const PRIVILEGES = {
  ADD_BOOK: 'ADD_BOOK',
  UPDATE_BOOK: 'UPDATE_BOOK',
  DELETE_BOOK: 'DELETE_BOOK',
  ISSUE_BOOK: 'ISSUE_BOOK',
  RETURN_BOOK: 'RETURN_BOOK',
  VIEW_BOOK: 'VIEW_BOOK',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_FINANCE: 'MANAGE_FINANCE',
}
